"""
Autogenerated setup configuration for Sifry - Substitution Cipher Library

Generated by Perplexity Sonar

This file configures the package for installation and distribution.

This file might be wrong, please be mindful when using AI-generated code, I haven't personally checked it -JW
"""

from setuptools import setup, find_packages
import os

# Read the README file
def read_file(filename):
    """Read file content."""
    filepath = os.path.join(os.path.dirname(__file__), filename)
    if os.path.exists(filepath):
        with open(filepath, 'r', encoding='utf-8') as f:
            return f.read()
    return ''

long_description = read_file('README.md')
requirements = read_file('requirements.txt').strip().split('\n')

setup(
    # Basic Project Information
    name='sifry',
    version='0.1.0',
    description='Substitution cipher library with cryptanalysis using Metropolis-Hastings algorithm',
    long_description=long_description,
    long_description_content_type='text/markdown',

    # Author Information
    author='Jozef Waldhauser',
    author_email='your.email@example.com',
    maintainer='Jozef Waldhauser',
    maintainer_email='your.email@example.com',

    # Project URLs
    url='https://github.com/Jozefwl/mipy-sifry',
    project_urls={
        'Bug Tracker': 'https://github.com/Jozefwl/mipy-sifry/issues',
        'Documentation': 'https://github.com/Jozefwl/mipy-sifry',
        'Source Code': 'https://github.com/Jozefwl/mipy-sifry',
    },

    # License
    license='MIT',

    # Package Discovery
    packages=find_packages(exclude=['tests', 'docs', 'notebooks', 'data']),

    # Dependencies
    install_requires=[
        'numpy>=1.19.0',
        'requests>=2.25.0',
    ],

    # Optional dependencies for development
    extras_require={
        'dev': [
            'pytest>=6.0',
            'pytest-cov>=2.10.0',
            'black>=20.8b1',
            'flake8>=3.8.0',
        ],
        'notebook': [
            'jupyter>=1.0.0',
            'matplotlib>=3.3.0',
            'scipy>=1.5.0',
        ],
    },

    # Python Version Requirement
    python_requires='>=3.7',

    # Classification
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers',
        'Intended Audience :: Education',
        'Topic :: Security :: Cryptography',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Operating System :: OS Independent',
    ],

    # Keywords
    keywords='cipher cryptography cryptanalysis substitution czech',

    # Include package data
    include_package_data=True,

    # Entry points (optional - for CLI tools)
    entry_points={
        'console_scripts': [
            # Example: 'sifry-cli=sifry.cli:main',
        ],
    },

    # Zip safety
    zip_safe=False,
)
